#!/usr/bin/env bash
# tools/install-hooks.sh
# Installs git hooks that catch the common mistakes we've hit in this repo:
#   - bad commit messages
#   - merged conflict markers
#   - missing header guards
#   - CRLF/space pollution
#
# Re-run safely any time. Idempotent.

set -euo pipefail
repo_root=$(git rev-parse --show-toplevel)
hooks_dir="$repo_root/.git/hooks"

mkdir -p "$hooks_dir"
chmod +x "$repo_root/tools"/*.sh

# commit-msg: enforce conventional commit + fix-spam block
cat > "$hooks_dir/commit-msg" <<'HOOK'
#!/usr/bin/env bash
# Generated by tools/install-hooks.sh — do not edit by hand.
msg_file="$1"
msg=$(cat "$msg_file")

# 1. Conventional commit prefix required
if ! printf '%s' "$msg" | head -n1 | grep -qE '^(feat|fix|refactor|perf|test|docs|build|ci|chore|style)(\([a-z0-9_-]+\))?!?: '; then
    echo "commit-msg: subject must start with conventional type."
    echo "  feat:  | fix: | refactor: | perf: | test: | docs: | build: | ci: | chore: | style:"
    echo "  optional scope: feat(shm): ..."
    echo "  See .gitmessage for examples."
    exit 1
fi

# 2. Block 3+ consecutive fix: commits
bash "$(git rev-parse --show-toplevel)/tools/check_fix_spam.sh" < "$msg_file"
HOOK

# pre-commit: header guards + cppcheck on staged C++ files
cat > "$hooks_dir/pre-commit" <<'HOOK'
#!/usr/bin/env bash
# Generated by tools/install-hooks.sh — do not edit by hand.
repo_root=$(git rev-parse --show-toplevel)
bash "$repo_root/tools/lint_header_guards.sh"
HOOK

# commit-msg + pre-commit must be executable
chmod +x "$hooks_dir/commit-msg" "$hooks_dir/pre-commit"

# Set the commit template (one-time, idempotent)
git config commit.template "$repo_root/.gitmessage"

echo "Hooks installed:"
echo "  - commit-msg: conventional + fix-spam guard"
echo "  - pre-commit: header guard lint"
echo "  - commit template: .gitmessage"
echo
echo "If you have pre-commit (https://pre-commit.com) installed, also run:"
echo "  pre-commit install"
